# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('gender', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(upload_to='icons')),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
